# Generated by Django 4.0 on 2021-03-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('startdate', models.CharField(max_length=200)),
                ('enddate', models.CharField(max_length=200)),
            ],
        ),
    ]
