# Generated by Django 4.0 on 2021-03-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headcount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
