# Generated by Django 4.0 on 2021-03-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headcount', '0002_alter_user_company_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, unique=True)),
                ('month', models.CharField(max_length=200)),
                ('headcount', models.CharField(max_length=200)),
            ],
        ),
    ]
