# Generated by Django 4.0 on 2021-03-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headcount', '0003_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='headcount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(),
        ),
    ]
