# Generated by Django 4.0 on 2021-03-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headcount', '0005_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='headcount',
            field=models.CharField(max_length=200),
        ),
    ]
