# Generated by Django 4.0 on 2021-03-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headcount', '0006_alter_company_headcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=200),
        ),
    ]
