# Generated by Django 4.0 on 2021-03-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headcount', '0008_alter_company_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='month',
            field=models.DateField(default=None, null=True),
        ),
    ]
